### ISSUE TITLE
Contination error

### ISSUE THREAD

**Issue by jcubic** [strtok/marwood#2]
An example that should evaluate to `10 #t`:

```scheme
(let ((called #f))
  (display (let ((my-val (call/cc (lambda (c) c))))
             (if (procedure? my-val)
                 (my-val 10)
                 (begin
                   (set! called #t)
                   my-val))))
  (newline)
  (display called)
  (newline))
```

It prints `#<continuation> #t`. This is from my unit tests (they don't run yet because LIPS don't support call/cc yet). https://github.com/jcubic/lips/blob/master/tests/continuations.scm

I'm not sure if you can run NodeJS unit tests but if you will run WASM in Node with a bit of modification you can use my unit tests. If possible I would like to have a link to my project.

**Comment by strtok** [comment]
Fortunately this was just a bug where procedure? returned #f for continuations. Fixed in 89a595a.
